apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitled-registry-credentials
  namespace: ci
spec:
  encryptedData:
    IBM_ENTITLED_REGISTRY_PASSWORD: AgC6FDVZvA54g/3g9i71tnbQKj3w8dp9+L9DXecwhTtYEeaoUAq1j0KADvZyu2uOT7esvikCTm86BRsNs3lOivAmSlXUSEH71q5/0z572Vpkt9XGJRIPQmLuheLtB4D29R77iwNNWwxzNkAy+XhVEOBpZgp3JRg21ocZ5wOm7rEIUZ6tPdMNqULr+bXkRmI7y7t+iyp6Gx9CAuGS+u40fDBbCvKPA/fSLZmLAhxzuyou9EKLz3USSXyOuvLtfuX9MJmncGYRbhRtVbqmynydRZRJ4/Lhuk/eIj7mEAhs0aUlESR7kIxoT51xOIohvzKpg9D+ul+ddE4KWn3Zvw1IUSPQb+3VcRNiZVNcBAOXKP54bYwz0PJwllHC3ph1e/ASatMqRbCliw5CH5jv5/G+oUjQpJJPgVCDTFBxbh7nIt7iHVPSPKfuRX/qRwThu3UhIc4aPJyZ8dvFXhVem3/o7QEczh5leAzvPOqzpb4oA058WYvPpDCr7UEX/dqedgrXJJ5rUYW1tbwmfmhfyyH5dz1pDl8mzXpjP/PDmRe4MiyiLB/0oFH/RnPzzj86oPc5+StzNz0JMyQiEz38beoIDgT5rGSxo9V5e+80kdwOedOWo6iGjYsOZ5umIvlyvJRBXMzHmmYKv21Fm7A55yYzO3Z2P45xIVVIGXHuIL8vmeDboo2XeJI5jJt3U9etM2BgR7JZx3i+NQNCOM1kbIHixTVzn7mA29NeWF/K5Vrjj9wJkWJLfkwoXbBWgb4jz3tmtYIzDh2LGHhWkRjRAlVf7+yUqxG7gj/HUCUSRDszQRgb9OA8n6x19Dt1rLTw5Qcn9TYKKhldVldShcAp84EtHYh2gULMcVWrehjDLHIIZkavFCtFJ85yZOJHsGhSBgUkN+KSj65jEhSkMJdlNSOwgPc6KmstUl/icNcTSx6GAYfMFg==
    IBM_ENTITLED_REGISTRY_USER: AgC/lKmC9/882lPWVqRGKx+t0ypeFQpIuYypZEZuu60JyzA9OrTigIItPPcwkHMTx65r8dQFM98LRzJUpmDQKzx1sNa6N5JXk0HtY+kmMggkNaLue5IXgRCUEETLUiPJLXFqamCea9cxS/CXbfh+x7CU/6DdskHdwvLBF0fW7bKz/ziQ9AOYNN+POEiF9SjPwCnwIQNtnmv70B+p5HL8jWwf8eW01NMdOH15hy+Uu6UhBXxhFCjxUjNh5sOVS4SX2yr1XR/TdaThPf/O+GNueUbkSEsnPcq5xlJiIQEIWmufLXR8k3hyRLoUx7i6bNtBveGTJ53PF+6cvItJGw6EO1hlH1y/owzhHEFhXyQEd2TxfzhUjasrD2BIM5lP97/b5/RsvEE0nWk7ASoAzOGYwh56Xqpic+FZYdtRSdpZq+3DlLyzY3fDfQCf3PlSjcGHRFDtYzEKFh3m9qxNiL5RXp3ny5oQiw6m5PReAKfJjndp8BgbfPJwZC92WkUX+TLjK2jUKg6Hyl3zREqdrPxZI6IWaFiQ8kKRxjdDda3BjOcoffYm9Y1n8ZuF6yUCX9uJmsLa67yTxWRYTYqk5NPKizkhdLr9LLP9xicAfG9NY+Qhjlwb1C+R3EYbC5IDSwbggEnc7WLK51sAoe2hXNFQi85ZEn0CwN4KDL4/eplDIajOSvKTKKHOC4h7GMZpgB7mfz9DYw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitled-registry-credentials
      namespace: ci

